table revenue_expense
	lineageTag: b2334066-6d56-47fe-8e71-a1b12635fa12

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 7cde603e-7889-478d-8361-d6f56b861ef8
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Business Line'
		dataType: string
		lineageTag: 8774423b-b808-4005-b78b-dcdb6f37078c
		summarizeBy: none
		sourceColumn: Business Line

		annotation SummarizationSetBy = Automatic

	column 'Expense subgroup'
		dataType: string
		lineageTag: 7377a1c2-6788-4e0c-abeb-b776a98a0b94
		summarizeBy: none
		sourceColumn: Expense subgroup

		annotation SummarizationSetBy = Automatic

	column 'Revenue / Expense Group'
		dataType: string
		lineageTag: 983d7283-919e-4999-a21a-ea5759fc8419
		summarizeBy: none
		sourceColumn: Revenue / Expense Group

		annotation SummarizationSetBy = Automatic

	column 'Revenue or expense'
		dataType: string
		lineageTag: 75178280-4c2c-4f37-8a01-0b039fb3fd23
		summarizeBy: none
		sourceColumn: Revenue or expense

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: int64
		formatString: 0
		lineageTag: 0e393ab2-e65b-405d-922d-834b25a9e6af
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

	partition revenue_expense = m
		mode: import
		source =
				let
				    Source = Source_File,
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Year", Int64.Type}, {"Month - name", type text}, {"Month -sequence", Int64.Type}, {"Date", type date}, {"Business Line", type text}, {"Amount, $", Int64.Type}, {"Expense subgroup", type text}, {"Revenue / Expense Group", type text}, {"Revenue or expense", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Year", "Month - name", "Month -sequence"}),
				    #"Inserted Absolute Value" = Table.AddColumn(#"Removed Columns", "Amount", each Number.Abs([#"Amount, $"]), type number),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Inserted Absolute Value",{{"Amount", Int64.Type}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Changed Type1",{"Amount, $"})
				in
				    #"Removed Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

