table revenue_expense
	lineageTag: b2334066-6d56-47fe-8e71-a1b12635fa12

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 7cde603e-7889-478d-8361-d6f56b861ef8
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Amount_
		dataType: int64
		formatString: 0
		lineageTag: 0e393ab2-e65b-405d-922d-834b25a9e6af
		summarizeBy: sum
		sourceColumn: Amount_

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 1cdbb779-67e8-4e47-93b5-65f162ea1164
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month_name
		dataType: string
		lineageTag: 15cf64b2-1aff-47f0-aa2d-403d977db726
		summarizeBy: none
		sourceColumn: Month_name

		annotation SummarizationSetBy = Automatic

	column Month_sequence
		dataType: int64
		formatString: 0
		lineageTag: fb703c96-c8c3-49cf-80ab-48d51fa09552
		summarizeBy: sum
		sourceColumn: Month_sequence

		annotation SummarizationSetBy = Automatic

	column Business_Line
		dataType: string
		lineageTag: c12e6637-4c85-4c22-a5d2-ae6cd89ffb21
		summarizeBy: none
		sourceColumn: Business_Line

		annotation SummarizationSetBy = Automatic

	column Expense_subgroup
		dataType: string
		lineageTag: 38e41957-9630-4ff3-83ac-f18892fd67a5
		summarizeBy: none
		sourceColumn: Expense_subgroup

		annotation SummarizationSetBy = Automatic

	column Revenue_Expense_Group
		dataType: string
		lineageTag: 8ed05b22-f169-4bba-afae-0a3a24005c26
		summarizeBy: none
		sourceColumn: Revenue_Expense_Group

		annotation SummarizationSetBy = Automatic

	column Revenue_or_expense
		dataType: string
		lineageTag: 11a489b2-5164-4bf6-a81f-48f455b1a973
		summarizeBy: none
		sourceColumn: Revenue_or_expense

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: int64
		formatString: 0
		lineageTag: 3daa09e7-9ea2-43ea-bb6e-537a6a4a444b
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

	partition revenue_expense = m
		mode: import
		source =
				let
				    Source = #"Onyx Data - Source_File",
				    #"Inserted Absolute Value1" = Table.AddColumn(Source, "Absolute Value", each Number.Abs([Amount])),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Inserted Absolute Value1",{{"Amount", Int64.Type}, {"Absolute Value", Int64.Type}, {"Year", Int64.Type}, {"Month_sequence", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"Amount", "Amount_"}, {"Absolute Value", "Amount"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

