table Source_File
	lineageTag: f1307e19-64b2-467b-9c1e-74a096e9f478

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 4c3a113c-5b02-409e-a68d-b17dd9c46654
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Month - name'
		dataType: string
		lineageTag: 86ec3ef5-eb31-4889-82e0-221cb3aad450
		summarizeBy: none
		sourceColumn: Month - name

		annotation SummarizationSetBy = Automatic

	column 'Month -sequence'
		dataType: int64
		formatString: 0
		lineageTag: ad5e2dd9-878c-42d3-9181-5e2f102ebfd2
		summarizeBy: sum
		sourceColumn: Month -sequence

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1f1e678b-8cf1-4ec4-bf0b-cc9c6df616d0
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Business Line'
		dataType: string
		lineageTag: 94d41e5a-551c-46b8-842a-52dca1fc70de
		summarizeBy: none
		sourceColumn: Business Line

		annotation SummarizationSetBy = Automatic

	column 'Amount, $'
		dataType: int64
		formatString: 0
		lineageTag: 732f98fa-15cf-4a43-b8a8-805049a585fe
		summarizeBy: sum
		sourceColumn: Amount, $

		annotation SummarizationSetBy = Automatic

	column 'Expense subgroup'
		dataType: string
		lineageTag: ac1d526c-4eb7-4619-bdf7-cabdfb198eaa
		summarizeBy: none
		sourceColumn: Expense subgroup

		annotation SummarizationSetBy = Automatic

	column 'Revenue / Expense Group'
		dataType: string
		lineageTag: 3bac95e9-96c3-4fb2-b8f7-306ab3fb50cd
		summarizeBy: none
		sourceColumn: Revenue / Expense Group

		annotation SummarizationSetBy = Automatic

	column 'Revenue or expense'
		dataType: string
		lineageTag: 55b68df8-c5a6-4998-8bfa-d7395aab07b2
		summarizeBy: none
		sourceColumn: Revenue or expense

		annotation SummarizationSetBy = Automatic

	partition Source_File = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://github.com/Theophine/Gym_Finance_Analysis-Power-BI-/raw/refs/heads/main/Onyx%20Data%20-%20DataDNA%20Dataset%20Challenge%20-%20Business%20Financial%20Dataset%20-%20August%202024.xlsx"), null, true),
				    Table1_Table = Source{[Item="Table1",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Table1_Table,{{"Year", Int64.Type}, {"Month - name", type text}, {"Month -sequence", Int64.Type}, {"Date", type date}, {"Business Line", type text}, {"Amount, $", Int64.Type}, {"Expense subgroup", type text}, {"Revenue / Expense Group", type text}, {"Revenue or expense", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

